/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type ActivityStatus = typeof ActivityStatus[keyof typeof ActivityStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
