/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { FarmerCropCalendarActivity } from './farmerCropCalendarActivity';

export interface ActivityDetails {
  pendingActivities?: FarmerCropCalendarActivity[] | null;
  calendarActivities?: FarmerCropCalendarActivity[] | null;
}
