/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';

export interface AdBannerResponse {
  id?: string;
  name?: LanguageName;
  imageUrl?: string | null;
  isActive?: boolean;
}
