/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { AdBannerResponse } from './adBannerResponse';

export interface AdBannerPaginatedResponse {
  totalCount?: number;
  skip?: number | null;
  take?: number | null;
  adBannerResponses?: AdBannerResponse[] | null;
}
