/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface AddressResponse {
  id?: string;
  fullName?: string | null;
  mobileNumber?: string | null;
  streetAddress?: string | null;
  country?: string | null;
  governorate?: string | null;
  town?: string | null;
  postalCode?: string | null;
  makeAsDefault?: boolean | null;
  userId?: string | null;
  countryCode?: string | null;
  callingCode?: string | null;
}
