/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface AdministrativeArea {
  id?: string | null;
  localizedName?: string | null;
  englishName?: string | null;
  level?: number;
  localizedType?: string | null;
  englishType?: string | null;
  countryID?: string | null;
}
