/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CalendarActivityResponse } from './calendarActivityResponse';

export interface CalendarActivityPaginatedResponse {
  totalCount?: number;
  calendarActivityResponse?: CalendarActivityResponse[] | null;
}
