/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { ActivityStatus } from './activityStatus';

export interface CalendarActivityStatusRequest {
  cropId?: string;
  farmId?: string;
  calendarId?: string;
  activityId?: string;
  activityDate?: string | null;
  activityStatus?: ActivityStatus;
  activityOrder?: number | null;
  farmerId?: string | null;
}
