/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface CalendarActivityRequest {
  id?: string | null;
  calendarId?: string | null;
  activityId?: string | null;
  activityStartDay?: number | null;
  numberOfActivityDays?: number | null;
  repeatActivityDays?: number | null;
  repeatActivityInterval?: number | null;
  activityOrder?: number | null;
  enDescription?: string | null;
  arDescription?: string | null;
  imageUrl?: number | null;
}
