/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';

export interface CalendarActivityResponse {
  id?: string | null;
  activityId?: string | null;
  calendarId?: string | null;
  calendarNames?: LanguageName;
  activityName?: LanguageName;
  activityStartDay?: number | null;
  numberOfActivityDays?: number | null;
  repeatActivityDays?: number | null;
  repeatActivityInterval?: number | null;
  activityOrder?: number | null;
  enDescription?: string | null;
  arDescription?: string | null;
  imageUrl?: number | null;
}
