/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Image } from './image';
import type { Item } from './item';

export interface Channel {
  title?: string | null;
  link?: string[] | null;
  description?: string | null;
  language?: string | null;
  lastBuildDate?: string | null;
  copyright?: string | null;
  docs?: string | null;
  generator?: string | null;
  ttl?: number;
  image?: Image;
  item?: Item[] | null;
}
