/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Governorate } from './governorate';

export interface City {
  id?: string;
  updatedBy?: string | null;
  createdBy: string;
  updatedOn?: string | null;
  isActive?: boolean;
  isDeleted?: boolean | null;
  enName?: string | null;
  arName?: string | null;
  governorate?: Governorate;
  governorateId?: string | null;
}
