/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface Coordinate {
  longitude?: string | null;
  latitude?: string | null;
}
