/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface CostCalculationModel {
  id?: string | null;
  calculation?: string | null;
  createdOn?: string;
  updatedOn?: string | null;
}
