/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';
import type { CropCategoryModel } from './cropCategoryModel';

export interface CropModel {
  name?: LanguageName;
  description?: string | null;
  imageUrl?: string | null;
  cropCategory?: CropCategoryModel;
  cropCategoryId?: string | null;
  colorCode?: string | null;
  farmonautCropCode?: string | null;
}
