/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface CropBasicResponse {
  id?: string | null;
  name?: string | null;
  colorCode?: string | null;
  imageUrl?: string | null;
}
