/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface CropSolutionRequest {
  uid?: string | null;
  cropCode?: string | null;
}
