/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { UpdatedCropCalendarActivityRequest } from './updatedCropCalendarActivityRequest';

export interface CropIdsActivitiesRequest {
  cropIds?: string | null;
  calendarName?: string | null;
  activities?: UpdatedCropCalendarActivityRequest[] | null;
}
