/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface CropResponse {
  id?: string | null;
  name?: string | null;
  cropCategoryId?: string;
  cropCategoryName?: string | null;
  description?: string | null;
  createdOn?: string;
  updatedBy?: string | null;
  createdBy?: string | null;
  updatedOn?: string | null;
  isActive?: boolean;
  colorCode?: string | null;
  imageUrl?: string | null;
}
