/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CropCategoryResponse } from './cropCategoryResponse';

export interface CropCategoryPaginatedResponse {
  totalCount?: number;
  skip?: number | null;
  take?: number | null;
  cropCategoryResponses?: CropCategoryResponse[] | null;
}
