/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface CropRequest {
  id?: string | null;
  name?: string | null;
  description?: string | null;
  imageUrl?: string | null;
  cropCategoryId?: string | null;
  isActive?: boolean | null;
}
