/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface CropCategoryRequest {
  name?: string | null;
  description?: string | null;
  id?: string | null;
  isActive?: boolean | null;
}
