/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CropBasicResponse } from './cropBasicResponse';
import type { CoOrdinates } from './coOrdinates';

export interface CultivationDetailResponse {
  cropDetails?: CropBasicResponse;
  area?: number | null;
  cultivationTime?: string | null;
  soilTypeId?: string | null;
  coordinates?: CoOrdinates[] | null;
}
