/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CoOrdinates } from './coOrdinates';

export interface CultivationDetailRequest {
  id?: string | null;
  cropId?: string | null;
  farmId?: string | null;
  area?: number | null;
  cultivationTime?: string | null;
  soilTypeId?: string | null;
  coordinates?: CoOrdinates[] | null;
}
