/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CropBasicResponse } from './cropBasicResponse';
import type { CoOrdinates } from './coOrdinates';

export interface CultivationDetailResponse {
  farmCropId?: string;
  cropDetails?: CropBasicResponse;
  area?: number | null;
  harvestDate?: string | null;
  sowingDate?: string | null;
  quantity?: number | null;
  typeOfIrrigation?: number | null;
  coordinates?: CoOrdinates[] | null;
  alowedArea?: number | null;
  fieldId?: string | null;
}
