/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CurrentConditionsPrecipitationType } from './currentConditionsPrecipitationType';
import type { Temperature } from './temperature';
import type { RealFeelTemperature } from './realFeelTemperature';
import type { RealFeelTemperatureShade } from './realFeelTemperatureShade';
import type { DewPoint } from './dewPoint';
import type { Wind } from './wind';
import type { WindGust } from './windGust';
import type { Visibility } from './visibility';
import type { Ceiling } from './ceiling';
import type { Pressure } from './pressure';
import type { PressureTendency } from './pressureTendency';
import type { Past24HourTemperatureDeparture } from './past24HourTemperatureDeparture';
import type { ApparentTemperature } from './apparentTemperature';
import type { WindChillTemperature } from './windChillTemperature';
import type { WetBulbTemperature } from './wetBulbTemperature';
import type { Precip1hr } from './precip1hr';
import type { PrecipitationSummary } from './precipitationSummary';
import type { TemperatureSummary } from './temperatureSummary';
import type { LocationDetails } from './locationDetails';

export interface CurrentConditions {
  localObservationDateTime?: string;
  epochTime?: number;
  weatherText?: string | null;
  weatherIcon?: number;
  hasPrecipitation?: boolean;
  precipitationType?: CurrentConditionsPrecipitationType;
  isDayTime?: boolean;
  temperature?: Temperature;
  realFeelTemperature?: RealFeelTemperature;
  realFeelTemperatureShade?: RealFeelTemperatureShade;
  relativeHumidity?: number;
  indoorRelativeHumidity?: number;
  dewPoint?: DewPoint;
  wind?: Wind;
  windGust?: WindGust;
  uvIndex?: number;
  uvIndexText?: string | null;
  visibility?: Visibility;
  obstructionsToVisibility?: string | null;
  cloudCover?: number;
  ceiling?: Ceiling;
  pressure?: Pressure;
  pressureTendency?: PressureTendency;
  past24HourTemperatureDeparture?: Past24HourTemperatureDeparture;
  apparentTemperature?: ApparentTemperature;
  windChillTemperature?: WindChillTemperature;
  wetBulbTemperature?: WetBulbTemperature;
  precip1hr?: Precip1hr;
  precipitationSummary?: PrecipitationSummary;
  temperatureSummary?: TemperatureSummary;
  mobileLink?: string | null;
  link?: string | null;
  locationDetails?: LocationDetails;
}
