/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface Direction {
  degrees?: number;
  localized?: string | null;
  english?: string | null;
}
