/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CropModel } from './cropModel';
import type { FarmModel } from './farmModel';
import type { CalendarModel } from './calendarModel';
import type { CoOrdinates } from './coOrdinates';

export interface FarmCropModel {
  farmCropId?: string;
  cropId?: string;
  cropModel?: CropModel;
  farmId?: string;
  farmData?: FarmModel;
  calendarId?: string | null;
  calendar?: CalendarModel;
  area?: number | null;
  sowingDate?: string | null;
  harvestDate?: string | null;
  quantity?: number | null;
  typeOfIrrigation?: number | null;
  coordinates?: CoOrdinates[] | null;
  allowedArea?: number;
  fieldId?: string | null;
}
