/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { FarmPoints } from './farmPoints';

export interface Farm {
  uid?: string | null;
  cropCode?: string | null;
  fieldName?: string | null;
  paymentType?: number;
  points?: FarmPoints;
}
