/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';

export interface FarmerCropCalendarActivity {
  activityName?: LanguageName;
  activityId?: string;
  activityDate?: string;
  activityDesc?: LanguageName;
  imageUrl?: number | null;
  activityOrder?: number | null;
}
