/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CoOrdinates } from './coOrdinates';

export interface FarmResponse {
  id?: string;
  name?: string | null;
  landHoldingNumber?: string | null;
  governorateFieldId?: string;
  irrigationTypeId?: string;
  coordinates?: CoOrdinates[] | null;
  createdOn?: string;
  updatedBy?: string | null;
  createdBy?: string | null;
  updatedOn?: string | null;
  isActive?: boolean;
}
