/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CoOrdinates } from './coOrdinates';

export interface FarmRequest {
  id?: string | null;
  name?: string | null;
  coordinates?: CoOrdinates[] | null;
  landHoldingNumber?: string | null;
  governorateFieldId?: string | null;
  irrigationTypeId?: string | null;
  cityId?: string | null;
  villageId?: string | null;
  address?: string | null;
  organization?: string | null;
}
