/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CropModel } from './cropModel';
import type { CoOrdinates } from './coOrdinates';

export interface FarmonautFarmCropModel {
  farmCropId?: string;
  cropId?: string;
  cropModel?: CropModel;
  farmId?: string;
  calendarId?: string | null;
  area?: number | null;
  sowingDate?: string | null;
  harvestDate?: string | null;
  quantity?: number | null;
  typeOfIrrigation?: number | null;
  coordinates?: CoOrdinates[] | null;
  allowedArea?: number;
  fieldId?: string | null;
}
