/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CoOrdinates } from './coOrdinates';
import type { FarmCropsDetailResponse } from './farmCropsDetailResponse';

export interface FarmResponse {
  id?: string;
  name?: string | null;
  landHoldingNumber?: string | null;
  governorateFieldId?: string;
  governorate?: string | null;
  irrigationTypeId?: string;
  irrigationType?: string | null;
  cityId?: string | null;
  city?: string | null;
  villageId?: string | null;
  village?: string | null;
  address?: string | null;
  organization?: string | null;
  coordinates?: CoOrdinates[] | null;
  createdOn?: string;
  updatedBy?: string | null;
  createdBy?: string | null;
  updatedOn?: string | null;
  isActive?: boolean;
  crops?: FarmCropsDetailResponse[] | null;
}
