/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CoOrdinates } from './coOrdinates';
import type { CultivationDetailResponse } from './cultivationDetailResponse';

export interface FarmCropCultivationResponse {
  totalCount?: number;
  skip?: number;
  take?: number;
  id?: string | null;
  farmId?: string | null;
  calendarId?: string | null;
  coordinates?: CoOrdinates[] | null;
  cultivationDetails?: CultivationDetailResponse[] | null;
}
