/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';
import type { SubscriptionStatus } from './subscriptionStatus';
import type { PlanFeature } from './planFeature';

export interface FarmerPlan {
  planId?: string | null;
  planName?: LanguageName;
  startDate?: string | null;
  endDate?: string | null;
  status?: SubscriptionStatus;
  planFeatures?: PlanFeature[] | null;
}
