/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { FarmCrops } from './farmCrops';

export interface FarmonautCropsRequest {
  farmCrops?: FarmCrops[] | null;
}
