/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CropBasicResponse } from './cropBasicResponse';

export interface FarmCropsResponse {
  farmId?: string | null;
  cropDetails?: CropBasicResponse[] | null;
}
