/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';
import type { FarmonautFarmCropModel } from './farmonautFarmCropModel';

export interface FarmonautFarm {
  farmId?: string | null;
  name?: LanguageName;
  farmCrops?: FarmonautFarmCropModel[] | null;
}
