/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { FarmCropModel } from './farmCropModel';

export interface FarmCropModelPaginated {
  totalCount?: number;
  skip?: number;
  take?: number;
  farmCrops?: FarmCropModel[] | null;
}
