/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { CropResponse } from './cropResponse';
import type { CoOrdinates } from './coOrdinates';

export interface FarmCropsDetailResponse {
  farmCropId?: string;
  crop?: CropResponse;
  area?: number | null;
  sowingDate?: string | null;
  harvestDate?: string | null;
  quantity?: number | null;
  typeOfIrrigation?: number | null;
  coordinates?: CoOrdinates[] | null;
  fieldId?: string | null;
}
