/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';
import type { CoOrdinates } from './coOrdinates';
import type { FarmCropsDetailResponse } from './farmCropsDetailResponse';

export interface FarmResponse {
  id?: string;
  name?: LanguageName;
  landHoldingNumber?: string | null;
  governorateId?: string;
  governorate?: LanguageName;
  irrigationTypeId?: string;
  irrigationType?: LanguageName;
  cityId?: string | null;
  city?: LanguageName;
  villageId?: string | null;
  village?: LanguageName;
  farmerId?: string | null;
  address?: string | null;
  organization?: string | null;
  coordinates?: CoOrdinates[] | null;
  createdOn?: string;
  updatedBy?: string | null;
  createdBy?: string | null;
  updatedOn?: string | null;
  isActive?: boolean;
  crops?: FarmCropsDetailResponse[] | null;
}
