/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { FieldAreaRequestPoints } from './fieldAreaRequestPoints';

export interface FieldAreaRequest {
  points?: FieldAreaRequestPoints;
  uid?: string | null;
}
