/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Coordinate } from './coordinate';

export type FieldAreaRequestPoints = {[key: string]: Coordinate} | null;
