/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { FieldCoordinatesRequestPoints } from './fieldCoordinatesRequestPoints';

export interface FieldCoordinatesRequest {
  uid?: string | null;
  fieldId?: string | null;
  points?: FieldCoordinatesRequestPoints;
}
