/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Elevation } from './elevation';

export interface GeoPosition {
  latitude?: number;
  longitude?: number;
  elevation?: Elevation;
}
