/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type GetApiSubscriptionGetSubscriptionFeaturesBySubscriptionIdParams = {
Id?: string;
skip?: number;
take?: number;
sortColumn?: string;
sortOrder?: string;
q?: string;
};
