/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type GetApiSubscriptionGetSubscriptionsParams = {
skip?: number;
take?: number;
q?: string;
sortColumn?: string;
sortOrder?: string;
};
