/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { NotificationType } from './notificationType';

export type GetApiNotificationGetallviewnotificationParams = {
skip?: number;
take?: number;
isRead?: boolean;
q?: string;
sortColumn?: string;
notificationType?: NotificationType;
sortOrder?: string;
};
