/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type GetApiWeatherGetWeatherDataParams = {
longitude?: string;
latitude?: string;
startDate?: string;
endDate?: string;
};
