/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface Image {
  title?: string | null;
  link?: string | null;
  url?: string | null;
  description?: string | null;
}
