/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface Imperial {
  value?: number;
  unit?: string | null;
  unitType?: number;
  phrase?: string | null;
}
