/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Source } from './source';
import type { Enclosure } from './enclosure';

export interface Item {
  title?: string | null;
  category?: string | null;
  link?: string | null;
  guid?: string | null;
  description?: string | null;
  pubDate?: string | null;
  source?: Source;
  enclosure?: Enclosure;
}
