/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Region } from './region';
import type { Country } from './country';
import type { AdministrativeArea } from './administrativeArea';
import type { TimeZone } from './timeZone';
import type { GeoPosition } from './geoPosition';

export interface LocationDetails {
  version?: number;
  key?: string | null;
  type?: string | null;
  rank?: number;
  localizedName?: string | null;
  englishName?: string | null;
  primaryPostalCode?: string | null;
  region?: Region;
  country?: Country;
  administrativeArea?: AdministrativeArea;
  timeZone?: TimeZone;
  geoPosition?: GeoPosition;
  isAlias?: boolean;
  supplementalAdminAreas?: unknown[] | null;
  dataSets?: string[] | null;
}
