/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { RoleModel } from './roleModel';

export interface LoginReturnModel {
  id?: string | null;
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  middleName?: string | null;
  token?: string | null;
  lastLoginDate?: string | null;
  currentLoginDate?: string | null;
  displayName?: string | null;
  phoneNumber?: string | null;
  roles?: RoleModel[] | null;
  message?: string | null;
}
