/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface MobileAppUserBasicDetails {
  id?: string;
  updatedBy?: string | null;
  createdBy: string;
  updatedOn?: string | null;
  isActive?: boolean;
  displayName: string;
  emailId?: string | null;
  mobileNumber?: string | null;
  firebaseUserId?: string | null;
}
