/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Metric } from './metric';
import type { Imperial } from './imperial';

export interface Past18Hours {
  metric?: Metric;
  imperial?: Imperial;
}
