/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Minimum } from './minimum';
import type { Maximum } from './maximum';

export interface Past24HourRange {
  minimum?: Minimum;
  maximum?: Maximum;
}
