/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface PhaseSubPhaseRequest {
  id?: string | null;
  phaseSubPhaseName?: string | null;
  parentId?: string | null;
  phaseSortOrder?: number | null;
  subPhaseSortOrder?: number | null;
}
