/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { LanguageName } from './languageName';
import type { FarmerServiceType } from './farmerServiceType';

export interface PlanFeature {
  featureId?: string | null;
  featureName?: LanguageName;
  farmerServiceTypes?: FarmerServiceType[] | null;
}
