/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { NotificationType } from './notificationType';

export type PostApiNotificationCreatenotificationParams = {
Id?: string;
MessageTitle?: string;
MessageBody?: string;
IsPushNow?: boolean;
NotificationType?: NotificationType;
};
