/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type PostApiAdBannerCreateUpdateAdBannerBody = {
  Id?: string;
  'Name.En'?: string;
  'Name.Ar'?: string;
  ImageUrl?: string;
  IsActive?: boolean;
  File?: Blob;
};
