/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type PostApiCropCreateUpdateCropBody = {
  Id?: string;
  EnName?: string;
  ArName?: string;
  Description?: string;
  ImageUrl?: string;
  ColorCode?: string;
  CropCategoryId?: string;
  IsActive?: boolean;
  File?: Blob;
  FarmonautCropCode?: string;
};
