/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type PostApiCropCreateUpdateCropCategoryBody = {
  'Name.En'?: string;
  'Name.Ar'?: string;
  Description?: string;
  Id?: string;
  IsActive?: boolean;
  ImageUrl?: string;
  File?: Blob;
};
