/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Precipitation } from './precipitation';
import type { PastHour } from './pastHour';
import type { Past3Hours } from './past3Hours';
import type { Past6Hours } from './past6Hours';
import type { Past9Hours } from './past9Hours';
import type { Past12Hours } from './past12Hours';
import type { Past18Hours } from './past18Hours';
import type { Past24Hours } from './past24Hours';

export interface PrecipitationSummary {
  precipitation?: Precipitation;
  pastHour?: PastHour;
  past3Hours?: Past3Hours;
  past6Hours?: Past6Hours;
  past9Hours?: Past9Hours;
  past12Hours?: Past12Hours;
  past18Hours?: Past18Hours;
  past24Hours?: Past24Hours;
}
