/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { NotificationType } from './notificationType';

export interface PushNotificationResponse {
  id?: string;
  messageTitle?: string | null;
  messageBody?: string | null;
  notificationType?: NotificationType;
  isProcessed?: boolean;
  createdBy?: string | null;
  createdOn?: string;
  updatedBy?: string | null;
  updatedOn?: string | null;
  isActive?: boolean;
}
