/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { PushNotificationResponse } from './pushNotificationResponse';

export interface PushNotificationPaginatedResponse {
  totalCount?: number;
  pushNotificationResponses?: PushNotificationResponse[] | null;
}
