/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { NotificationType } from './notificationType';

export interface PushNotificationModel {
  id?: string;
  messageTitle?: string | null;
  messageBody?: string | null;
  isPushNow?: boolean;
  notificationType?: NotificationType;
}
