/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { RoleModel } from './roleModel';

export interface RegisterModel {
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  phoneNumber?: string | null;
  isActive?: boolean;
  roles?: RoleModel[] | null;
}
