/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { RoleModel } from './roleModel';

export interface RegisterModel {
  email?: string | null;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  password?: string | null;
  isActive?: boolean;
  isMemberAccount?: boolean | null;
  message?: string | null;
  roles?: RoleModel[] | null;
}
