/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface ResetPasswordModel {
  email?: string | null;
  password: string;
  confirmPassword?: string | null;
  code?: string | null;
  userName?: string | null;
}
