/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Channel } from './channel';

export interface Rss {
  channel?: Channel;
  version?: number;
  atom?: string | null;
  dc?: string | null;
  text?: string | null;
}
