/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { ServiceModel } from './serviceModel';

export interface ServiceTypePaginatedResponse {
  totalCount?: number;
  skip?: number | null;
  take?: number | null;
  serviceResponse?: ServiceModel[] | null;
}
