/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface ServiceType {
  id?: string;
  updatedBy?: string | null;
  createdBy: string;
  updatedOn?: string | null;
  isActive?: boolean;
  isDeleted?: boolean | null;
  enTitle?: string | null;
  arTitle?: string | null;
  enDescription?: string | null;
  arDescription?: string | null;
}
