/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface SubscriptionPlanFeatureMapModel {
  id?: string;
  planId?: string | null;
  featureId?: string | null;
  featureValue?: string | null;
  isActive?: boolean;
}
