/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { SubscriptionPlanFeatureMapListModel } from './subscriptionPlanFeatureMapListModel';

export interface SubscriptionPlanFeatureMapListModelPagedResults {
  pageNumber?: number;
  pageSize?: number;
  totalNumberOfPages?: number;
  totalNumberOfRecords?: number;
  results?: SubscriptionPlanFeatureMapListModel[] | null;
}
