/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface SubscriptionFeatureModel {
  id?: string;
  enTitle?: string | null;
  arTitle?: string | null;
  serviceTypeId?: string | null;
  isActive?: boolean;
}
