/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export type SubscriptionStatus = typeof SubscriptionStatus[keyof typeof SubscriptionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionStatus = {
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
