/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { SubscriptionFeatureListModel } from './subscriptionFeatureListModel';

export interface SubscriptionFeatureListModelPagedResults {
  pageNumber?: number;
  pageSize?: number;
  totalNumberOfPages?: number;
  totalNumberOfRecords?: number;
  results?: SubscriptionFeatureListModel[] | null;
}
