/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface SubscriptionPlan {
  id?: string;
  updatedBy?: string | null;
  createdBy: string;
  updatedOn?: string | null;
  isActive?: boolean;
  isDeleted?: boolean | null;
  pricePerYear?: string | null;
  enTitle?: string | null;
  arTitle?: string | null;
  pricePerMonth?: string | null;
}
