/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { SubscriptionFeaturesModel } from './subscriptionFeaturesModel';

export interface SubscriptionFeatureResponse {
  totalCount?: number;
  skip?: number;
  take?: number;
  subscriptionResponse?: SubscriptionFeaturesModel[] | null;
}
