/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { SubscriptionPlanListModel } from './subscriptionPlanListModel';

export interface SubscriptionPlanPaginatedResponse {
  totalCount?: number;
  skip?: number | null;
  take?: number | null;
  subscriptionPlanResponse?: SubscriptionPlanListModel[] | null;
}
