/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface SubscriptionPlanModel {
  id?: string;
  pricePerYear?: string | null;
  enTitle?: string | null;
  arTitle?: string | null;
  pricePerMonth?: string | null;
  isActive?: boolean;
}
