/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { SubscriptionFeatureList } from './subscriptionFeatureList';

export interface SubscriptionFeaturePaginatedResponse {
  totalCount?: number;
  skip?: number | null;
  take?: number | null;
  subscriptionFeatureResponse?: SubscriptionFeatureList[] | null;
}
