/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface SubscriptionPlanFeatureMapListModel {
  id?: string;
  planId?: string | null;
  featureId?: string | null;
  featureValue?: string | null;
  createdOn?: string | null;
}
