/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Past6HourRange } from './past6HourRange';
import type { Past12HourRange } from './past12HourRange';
import type { Past24HourRange } from './past24HourRange';

export interface TemperatureSummary {
  past6HourRange?: Past6HourRange;
  past12HourRange?: Past12HourRange;
  past24HourRange?: Past24HourRange;
}
