/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { TimeZoneNextOffsetChange } from './timeZoneNextOffsetChange';

export interface TimeZone {
  code?: string | null;
  name?: string | null;
  gmtOffset?: number;
  isDaylightSaving?: boolean;
  nextOffsetChange?: TimeZoneNextOffsetChange;
}
