/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface UpdatedCropCalendarActivityRequest {
  id?: string | null;
  activityId?: string | null;
  days?: number | null;
  intervalInDays?: number | null;
  precedingActivityGap?: number | null;
  precedingActivityId?: string | null;
}
