/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { UpdatePolygonRequestCoordinates } from './updatePolygonRequestCoordinates';

export interface UpdatePolygonRequest {
  city?: string | null;
  coordinates?: UpdatePolygonRequestCoordinates;
  fieldID?: string | null;
  fullAddress?: string | null;
  name?: string | null;
  phoneNumber?: string | null;
  polygonID?: string | null;
  uid?: string | null;
}
