/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { RoleModel } from './roleModel';

export interface UpdateUserModel {
  id?: string | null;
  email: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  roles?: RoleModel[] | null;
  isActive?: boolean;
  createdOn?: string;
  updatedOn?: string | null;
  isLocked?: boolean;
  message?: string | null;
}
