/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { RoleModel } from './roleModel';

export interface UpdateUserModel {
  id?: string | null;
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  displayName?: string | null;
  phoneNumber: string;
  roles?: RoleModel[] | null;
  isActive?: boolean;
  isLocked?: boolean;
}
