/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface UpdatedCropCalendarActivityResponse {
  id?: string | null;
  activityId?: string | null;
  calendarName?: string | null;
  cropIds?: string | null;
  cropNames?: string | null;
  activityName?: string | null;
  days?: number | null;
  intervalInDays?: number | null;
  precedingActivityGap?: number | null;
  precedingActivityId?: string | null;
  precedingActivityName?: string | null;
  activityOrder?: number | null;
}
