/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { RoleUpdateModel } from './roleUpdateModel';

export interface UserModel {
  id?: string | null;
  email?: string | null;
  displayName?: string | null;
  token?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  fullName?: string | null;
  middleName?: string | null;
  gender?: string | null;
  dateOfBirth?: string | null;
  phoneNumber?: string | null;
  phoneNumber2?: string | null;
  address1?: string | null;
  address2?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  zipCode?: string | null;
  isActive?: boolean;
  isLocked?: boolean;
  status?: string | null;
  createdOn?: string | null;
  updatedOn?: string | null;
  roles?: RoleUpdateModel[] | null;
  lastLoginDate?: string | null;
  currentLoginDate?: string | null;
  profilePic?: string | null;
}
