/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { RoleUpdateModel } from './roleUpdateModel';

export interface UserModel {
  id?: string | null;
  email?: string | null;
  displayName?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  phoneNumber?: string | null;
  isActive?: boolean;
  isLocked?: boolean;
  createdOn?: string | null;
  updatedOn?: string | null;
  roles?: RoleUpdateModel[] | null;
  lastLoginDate?: string | null;
  currentLoginDate?: string | null;
  profilePic?: string | null;
}
