/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { UserModel } from './userModel';

export interface UsersPaginatedResponse {
  totalCount?: number;
  users?: UserModel[] | null;
}
