/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */

export interface UserPaymentInfo {
  planId?: string;
  orderAmount?: number;
  creditCardName?: string | null;
  cardNumber?: string | null;
  cardExpiryMonth?: string | null;
  cardExpiryYear?: string | null;
  cvv?: string | null;
}
