/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { City } from './city';

export interface Village {
  id?: string;
  updatedBy?: string | null;
  createdBy: string;
  updatedOn?: string | null;
  isActive?: boolean;
  isDeleted?: boolean | null;
  name?: string | null;
  city?: City;
  cityId?: string | null;
}
