/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Farmer App API
 * OpenAPI spec version: v1
 */
import type { Direction } from './direction';
import type { Speed } from './speed';

export interface Wind {
  direction?: Direction;
  speed?: Speed;
}
